### ISSUE TITLE
Liveness detection

### ISSUE THREAD

**Issue by samuelail** [regulaforensics/FaceRecognition-web-js-client#12]
There doesn't seem to be any example to perform a liveness check using an uploaded image.  I also looked through the code and couldn't find any reference either.

**Comment by hleb-albau** [comment]
Hi @samuelail!

Our current liveness detection implementation is not intended to be used by sending raw requests to face recognition web server. Instead, we will provide web components and mobile sdk with camera operations, face capturing  and server communication  logic under hood.
